apiVersion: v1
kind: ConfigMap
metadata:
  name: bookapp-configmap
  labels:
    {{- include "books.labels" . | nindent 4 }}
data:
  .env |
    POSTGRES_USER={{ .Values.configmapData.POSTGRES_USER }}
    POSTGRES_PASSWORD={{ .Values.configmapData.POSTGRES_PASSWORD }}
    POSTGRES_DB={{ .Values.configmapData.POSTGRES_DB }}
    POSTGRES_HOST={{ .Values.configmapData.POSTGRES_HOST }}
    DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    POSTGRES_PORT=5432
    REDIS_HOST={{ .Values.configmapData.REDIS_HOST }}
    RABBITMQ_HOST={{ .Values.configmapData.RABBITMQ_HOST }}
    RABBITMQ_USERNAME={{ .Values.configmapData.RABBITMQ_USERNAME }}
    RABBITMQ_PASSWORD={{ .Values.configmapData.RABBITMQ_PASSWORD }}
    SECRET_KEY={{ .Values.configmapData.SECRET_KEY }}