fullnameOverride: "books"
replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: ""
  
serviceAccount:
  create: false

service:
  type: ClusterIP
  port: 80

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

podAnnotations: {}

podSecurityContext: {}

securityContext: {}



global:
  nodeSelector: {}

  tolerations: []

  affinity: {}

  service:
    type: ClusterIP
    port: 80